### ISSUE TITLE
minor typos among the files

### ISSUE THREAD

**Issue by Max-Z80** [stuartpullinger/icat_install#13]
file 00Introduction.md
  ... to give the reader aN introduction ...

file 02Prerequisites.md
  ICAT requires at least JDK verSion 1.8.

file 04InstallingAuthentication.md
  The two terms can be used interchangEably.

file 09Topcat.md
  TopCat is the easy to use front-end to the ICAT catalogue. It provides the SCIENTISTS with a familiar web interface

**Comment by stuartpullinger** [comment]
Fixed in #16
